/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import BaseEntity from "../base/BaseEntity";

export default class Payment extends BaseEntity {

    /**
     * 订单编号
     */
    orderNo: string | null = null;

    /**
     * 支付方式 ALIPAY/WEIXIN 支付宝/微信
     */
    method: string | null = null;

    /**
     * 支付平台订单号
     */
    thirdTransactionNo: string | null = null;

    /**
     * 金额(单位：分)
     */
    amount: number | null = null;

    /**
     * 支付状态 UNPAID/PAID/CLOSED 未支付/已支付/已关闭
     */
    status: string | null = null;


    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

    }

}






