/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import BaseEntity from "../base/BaseEntity";
import {ColumnStatus} from "./enums/ColumnStatus";

export default class Column extends BaseEntity {

    /**
     * 专栏名称
     */
    name: string | null = null;

    /**
     * 作者id
     */
    authorId: number | null = null;

    /**
     * 状态 NEW/OK/DISABLED 未发布/已生效/已禁用
     */
    status: ColumnStatus = ColumnStatus.NEW;


    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

    }

}






