/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import Base from "../base/Base";
import Column from "./Column";
import Author from "../author/Author";
import ColumnQuote from "../quote/ColumnQuote";
import Subscription from "../subscription/Subscription";

export default class RichColumn extends Base {

    /**
     * 专栏名称
     */
    column: Column = new Column();

    /**
     * 作者
     */
    author: Author = new Author();

    /**
     * 关联的报价
     */
    columnQuote: ColumnQuote = new ColumnQuote();


    /**
     * 关联的订阅情况
     */
    subscription: Subscription = new Subscription();


    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

        this.assignEntity("column", Column)
        this.assignEntity("author", Author)
        this.assignEntity("columnQuote", ColumnQuote)
        this.assignEntity("subscription", Subscription)

    }

}






