/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import BaseEntity from "../base/BaseEntity";

export default class Editor extends BaseEntity {

    /**
     * 用户名
     */
    username: string | null = null;

    /**
     * 密码
     */
    password: string | null = null;


    /**
     * 工号
     */
    workNo: string | null = null;


    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

    }

}






