/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import BaseEntity from "../base/BaseEntity";

export default class ColumnQuote extends BaseEntity {

    /**
     * 专栏id
     */
    columnId: number | null = null;

    /**
     * 编辑id
     */
    editorId: number | null = null;

    /**
     * 价格（单位：分）
     */
    price: number | null = null;

    /**
     * 报价状态 DISABLED/OK 未生效/已生效
     */
    status: string | null = null;

    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

    }

}






