/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import Base from "../base/Base";
import Order from "../order/Order";

export default class PrepareSubscribe extends Base {

    /**
     * 订单
     */
    orderDTO: Order = new Order();


    /**
     * 支付的一些token及信息
     */
    thirdTransactionNo: string | null = null;

    /**
     * 支付时候的验证信息等。
     */
    nonceStr: string | null = null;


    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

        this.assignEntity("orderDTO", Order)

    }

}






