/**
 * himmr.com Inc. Copyright (c) 2015-present All Rights Reserved.
 * generated by SaberGenerator
 */
import Base from "../base/Base";
import Subscription from "../subscription/Subscription";
import Column from "../column/Column";
import Reader from "../reader/Reader";
import Order from "../order/Order";

export default class RichSubscription extends Base {

    /**
     * 订阅情况
     */
    subscription: Subscription = new Subscription();

    /**
     * 专栏名称
     */
    column: Column = new Column();

    /**
     * 读者
     */
    reader: Reader = new Reader();

    /**
     * 关联的报价
     */
    order: Order = new Order();


    //*****************辅助字段********************//

    constructor() {
        super()
    }

    assign(obj: any) {
        super.assign(obj)

        this.assignEntity("subscription", Subscription)
        this.assignEntity("column", Column)
        this.assignEntity("reader", Reader)
        this.assignEntity("order", Order)

    }

}






